---
name: DetectionAlgorithmSettings
description: |
  List of parameter settings used in the `DetectionAlgorithm` for eye movement events.
anyOf:
  - type: object
    items:
      type: object
  - type: string
    enum:
      - n/a
